#!/bin/bash

echo "Downloading composer.phar"
curl -sS https://getcomposer.org/installer -o /tmp/composer-setup.php
HASH=`curl -sS https://composer.github.io/installer.sig`
php -r "if (hash_file('SHA384', '/tmp/composer-setup.php') === '$HASH') { echo 'Installer verified', PHP_EOL; exec('sudo php /tmp/composer-setup.php --install-dir=/usr/local/bin --filename=composer'); echo 'Install completed'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
